#pragma once

#define NN_SND_BTDMP_OUTPUT_FRAME_TRIG_FREQ (20)
#define NN_SND_BTDMP_OUTPUT_FIFO_SIZE       (16)
#define NN_SND_OUTPUT_RINGBUF_LOADUNIT      (NN_SND_BTDMP_OUTPUT_FIFO_SIZE * NN_SND_BTDMP_OUTPUT_FRAME_TRIG_FREQ)

#define NN_SND_SAMPLES_PER_FRAME            (NN_SND_OUTPUT_RINGBUF_LOADUNIT / 2)
#define NN_SND_USECS_PER_FRAME              ((NN_SND_SAMPLES_PER_FRAME * 1000000) / NN_SND_HW_I2S_CLOCK_32KHZ)

#define NN_SND_VOICE_NUM                    (24)