#pragma once

#define VER_STR_(version) #version
#define VER_STR(version) VER_STR_(version)

#define NN_VERSION_MAJOR 4
#define NN_VERSION_MINOR 2
#define NN_VERSION_MICRO 5
#define NN_VERSION_ID    200
#define NN_VERSION_PATCH "none"
#define NN_VERSION_SYSTEM_MAJOR   0
#define NN_VERSION_SYSTEM_MINOR   17
#define NN_VERSION_SYSTEM_MICRO   48
#define NN_VERSION_FIRMWARE_MAJOR 02
#define NN_VERSION_FIRMWARE_MINOR 35
#define NN_VERSION_FIRMWARE_MICRO 00

#define NN_VERSION_RVCT_MAJOR 4
#define NN_VERSION_RVCT_MINOR 1
#define NN_VERSION_RVCT_REV   791

#ifndef NN_CURRENT_SDK_VERSION
#define NN_CURRENT_SDK_VERSION "CTR_SDK-"VER_STR(NN_VERSION_MAJOR)"_"VER_STR(NN_VERSION_MINOR)"_"VER_STR(NN_VERSION_MICRO)"_"VER_STR(NN_VERSION_ID)"_"NN_VERSION_PATCH
#endif

#ifndef NN_CURRENT_FIRMWARE_VERSION
#define NN_CURRENT_FIRMWARE_VERSION "Firmware-"VER_STR(NN_VERSION_FIRMWARE_MAJOR)"_"VER_STR(NN_VERSION_FIRMWARE_MINOR)"_"VER_STR(NN_VERSION_FIRMWARE_MICRO)
#endif